# Generated by Django 3.2.4 on 2021-06-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210621_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, default='Hello'),
            preserve_default=False,
        ),
    ]
